### ISSUE TITLE
Blank page on Dimensions Setup

### ISSUE THREAD

**Issue by MaximePawlakFr** [myflyingbox/magento-extension#8]
Hello,
We are working on a Magento CE 1.9.3.7 and we installed MyFlyingBox v1.0.7

In Back-office, when we tried to go to Menu > Sales > MyFlyingBox > Dimensions Setup, we got a blank page and this kind of error : 
![screenshot from 2017-12-14 11-07-22](https://user-images.githubusercontent.com/10450830/33986797-ff99fa1a-e0be-11e7-8264-9350dbaa2169.png)

In Mfb > MyFlyingBox > etc > adminhtml.xml we changed the action about Dimension and we got in BO a liste of dimensions.

From 

```xml
<dimension translate="title" module="mfb_myflyingbox">
   <title>Dimensions setup</title>
   <action>adminhtml/myflyingbox_dimension/config</action>
   <sort_order>20</sort_order>
 </dimension>
```

to 

```xml
<dimension translate="title" module="mfb_myflyingbox">
   <title>Dimensions setup</title>
   <action>adminhtml/myflyingbox_dimension</action>
   <sort_order>20</sort_order>
 </dimension>
```

What should we expect from dimension/config ?

Regards

**Comment by tbelliard** [comment]
Voici une capture d'écran du formulaire supposé être affiché sur la page dimension/config : 

![capture d ecran_2017-12-14_12-51-25](https://user-images.githubusercontent.com/685797/33988641-a2266670-e0cd-11e7-92f4-92234abdc48c.png)

**Comment by MaximePawlakFr** [comment]
C'est bon. Il devait y avoir un souci sur mon workspace.
Par contre, on a remarqué un truc gênant : si le module n'est pas configuré, il va effectuer un appel API qui va foirer et qui va lancer une exception, bloquant certaines actions : comme la création d'un compte client.

**Comment by PofMagicfingers** [comment]
En réalité cela bloque le choix d'un mode de livraison dans le checkout, donc juste après la création d'un compte dans le cas ou il est dans le process de checkout. Magento attrape l'erreur et le client se retrouve redirigé sans pour autant être loggué ni avoir d'explication, alors que son compte est bien créé
